name: Wormhole Proof (WebRTC Tunnel)

on:
  workflow_dispatch:
    inputs:
      offer:
        description: 'Base64-encoded WebRTC offer from client'
        required: true
      profile:
        description: 'Twitter/X username to prove'
        required: true
        default: 'socrates1024'

jobs:
  prove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: cd wormhole && npm install

      - name: Start WebRTC tunnel
        env:
          OFFER: ${{ inputs.offer }}
        run: |
          cd wormhole
          node runner.js &
          RUNNER_PID=$!
          echo "RUNNER_PID=$RUNNER_PID" >> $GITHUB_ENV

          # Wait for SOCKS5 proxy (up to 3 min for ICE + connection)
          for i in {1..90}; do
            if nc -z 127.0.0.1 1080 2>/dev/null; then
              echo "SOCKS5 proxy ready!"
              break
            fi
            sleep 2
          done

          # Test tunnel
          EXIT_IP=$(curl --socks5 127.0.0.1:1080 -s --max-time 10 https://api.ipify.org || echo "tunnel-not-ready")
          echo "Exit IP: $EXIT_IP"

      - name: Capture proof
        env:
          SESSION_JSON: ${{ secrets.TWITTER_SESSION }}
        run: |
          mkdir -p proof
          cd wormhole
          node capture.js ${{ inputs.profile }}

      - name: Create certificate
        run: |
          cat > proof/certificate.json << EOF
          {
            "type": "wormhole-twitter-proof",
            "profile": "${{ inputs.profile }}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "github_run_id": "${{ github.run_id }}",
            "method": "webrtc-tunnel-via-logs"
          }
          EOF

      - name: Upload proof
        uses: actions/upload-artifact@v4
        with:
          name: wormhole-proof
          path: proof/

      - name: Cleanup
        if: always()
        run: kill $RUNNER_PID 2>/dev/null || true
